apiVersion: apps/v1
kind: Deployment
metadata:
  name: sakila-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sakila-app
  template:
    metadata:
      labels:
        app: sakila-app
    spec:
      containers:
        - name: sakila-app
          image: vaish/sakila-service
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://vaish-db-sakila.cxbxe7ypeoyt.us-east-1.rds.amazonaws.com:3306/vaishsakila
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_PASSWORD
